//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenAIDBExplorer.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenAIDBExplorer.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to database.
        /// </summary>
        internal static string ErrorConnectingToDatabase {
            get {
                return ResourceManager.GetString("ErrorConnectingToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to database (SQL).
        /// </summary>
        internal static string ErrorConnectingToDatabaseSQL {
            get {
                return ResourceManager.GetString("ErrorConnectingToDatabaseSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data dictionary source path does not exist..
        /// </summary>
        internal static string ErrorDataDictionarySourcePathDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorDataDictionarySourcePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deserializing table list result from call to model. Retrying....
        /// </summary>
        internal static string ErrorDeserializingTableListFromViewDefinition {
            get {
                return ResourceManager.GetString("ErrorDeserializingTableListFromViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting columns for table.
        /// </summary>
        internal static string ErrorGettingColumnsForTable {
            get {
                return ResourceManager.GetString("ErrorGettingColumnsForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting columns for view.
        /// </summary>
        internal static string ErrorGettingColumnsForView {
            get {
                return ResourceManager.GetString("ErrorGettingColumnsForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting indexes for table.
        /// </summary>
        internal static string ErrorGettingIndexesForTable {
            get {
                return ResourceManager.GetString("ErrorGettingIndexesForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting references for table.
        /// </summary>
        internal static string ErrorGettingReferencesForTable {
            get {
                return ResourceManager.GetString("ErrorGettingReferencesForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting sample data for table.
        /// </summary>
        internal static string ErrorGettingSampleDataForTable {
            get {
                return ResourceManager.GetString("ErrorGettingSampleDataForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting sample data for view.
        /// </summary>
        internal static string ErrorGettingSampleDataForView {
            get {
                return ResourceManager.GetString("ErrorGettingSampleDataForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting stored procedures from database.
        /// </summary>
        internal static string ErrorGettingStoredProceduresFromDatabase {
            get {
                return ResourceManager.GetString("ErrorGettingStoredProceduresFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting tables from database.
        /// </summary>
        internal static string ErrorGettingTablesFromDatabase {
            get {
                return ResourceManager.GetString("ErrorGettingTablesFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting definition for view.
        /// </summary>
        internal static string ErrorGettingViewDefinitionFromDatabase {
            get {
                return ResourceManager.GetString("ErrorGettingViewDefinitionFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting views from database.
        /// </summary>
        internal static string ErrorGettingViewsFromDatabase {
            get {
                return ResourceManager.GetString("ErrorGettingViewsFromDatabase", resourceCulture);
            }
        }
    }
}
